const MSG = {
  LOGIN: {
    PROMPT: 'LOGIN_PROMPT',
    SUCCESS: 'LOGIN_SUCCESS',
    FAILURE: 'LOGIN_FAILURE',
  },
  ROOM: {
    CREATE: 'ROOM_CREATE',
    JOIN: 'ROOM_JOIN',
    LEAVE: 'ROOM_LEAVE',
    UPDATE: 'ROOM_UPDATE',
  },
  GAME: {
    START: 'GAME_START',
    END: 'GAME_END',
    WAKE: 'GAME_WAKE',
    SLEEP: 'GAME_SLEEP',
    VOTE: 'GAME_VOTE',
    SUMMARY: 'GAME_SUMMARY',
    REVEAL: 'GAME_REVEAL',
  },
};

module.exports = MSG;
